# Generated by Django 6.0.4 on 2026-04-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('fire', 'Fire Staff'), ('crime', 'Crime Staff'), ('health', 'Health Staff'), ('accident', 'Accident Staff'), ('admin', 'Administrative Staff')], help_text='Assign emergency response role', max_length=20, null=True),
        ),
    ]
