# Generated by Django 6.0.4 on 2026-04-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='scene_image',
            field=models.ImageField(blank=True, null=True, upload_to='incident_images/'),
        ),
    ]
