# Generated by Django 6.0.4 on 2026-05-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0004_incident_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
