# Generated by Django 6.0.4 on 2026-05-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0005_smslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='sms_type',
            field=models.CharField(choices=[('new_incident', 'New Incident'), ('incident_update', 'Incident Update')], default='new_incident', max_length=30),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
