# Generated by Django 6.0.4 on 2026-10-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0006_smslog_sms_type_alter_smslog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='location_text',
            field=models.CharField(choices=[('Main Gate', 'Main Gate'), ('New Science Block', 'New Science Block'), ('Mass Communication', 'Mass Communication'), ('Entrepreneurship Centre', 'Entrepreneurship Centre'), ('ICT/Computer Building', 'ICT/Computer Building'), ('Faculty of Sciences', 'Faculty of Sciences'), ('Faculty of Computing', 'Faculty of Computing'), ('Faculty of Engineering', 'Faculty of Engineering'), ('Administrative Block', 'Administrative Block'), ('Senate Building', 'Senate Building'), ('MIS Building', 'MIS Building'), ('Student Affairs Unit', 'Student Affairs Unit'), ('SUG Secretariat', 'SUG Secretariat'), ('Lecture Theatre', 'Lecture Theatre'), ('Medical Unit', 'Medical Unit'), ('E-Library', 'E-Library'), ('Student Hostel', 'Student Hostel'), ('Bursary', 'Bursary'), ('Sports Complex', 'Sports Complex'), ('Staff Quarters', 'Staff Quarters'), ('Other', 'Other')], max_length=255),
        ),
    ]
